name: build-documentation

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-documentation:
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Documentation
        run: exec ./.github/scripts/build-docc.sh
      - name: Init Docs Branch
        run: |
          cd docs
          git init
          git add -A
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'deploy documentation'
      - name: Deploy GitHub Pages
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          force: true
          directory: ./docs
