name: build
on:
  workflow_dispatch:
  workflow_call:

env:
  DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build iOS
        run: exec ./.github/scripts/build.sh iOS
      - name: Build macOS
        run: exec ./.github/scripts/build.sh macOS
      - name: Build tvOS
        run: exec ./.github/scripts/build.sh tvOS
      - name: Build watchOS
        run: exec ./.github/scripts/build.sh watchOS
