name: CI - Pull Request
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  lint:
    name: SwiftLint
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  build:
    name: Build
    needs: lint
    uses: ./.github/workflows/build.yml
    secrets: inherit
