name: lint
on: push

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run SwiftLint
        run: |
          swiftlint --strict
