name: lint
on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/realm/swiftlint:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swiftlint --strict
